server:
  port: 8080  # Port for API Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: Auth-Service
          uri: http://localhost:9010
          predicates:
            - Path=/auth/**

        - id: citizen-service
          uri: http://localhost:9020
          predicates:
            - Path=/citizen/**

        - id: alert-service
          uri: http://localhost:9030
          predicates:
            - Path=/alerts/**








feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
